name: "ArgoCD Actions"
description: "Operate your ArgoCD applications from GitHub"
author: "omegion"
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  action:
    description: "Action name"
    required: true
  appName:
    description: "Application name to sync"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run argocd-actions CLI from Github Action REF
      run: |
        echo ${{ toJSON(github) }}
        action_path=${{ github.action_path }}
        echo ${action_path##*/}
        
        docker run --rm -i ghcr.io/omegion/argocd-actions:v1 \
          ${{ inputs.action }} \
          --application=${{ inputs.appName }} \
          --token=${{ inputs.token }} \
          --address=${{ inputs.address }} \
          --logLevel=debug
      shell: sh
